/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    ImageMerge: typeof import('./src/components/fl-image-processor/ImageMerge.vue')['default']
    ImageRegression: typeof import('./src/components/fl-image-processor/ImageRegression.vue')['default']
    MatchAndCrop: typeof import('./src/components/fl-image-processor/MatchAndCrop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpcFileConverter: typeof import('./src/components/SpcFileConverter.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
}
