/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImageMerge: typeof import('./src/components/fl-image-processor/ImageMerge.vue')['default']
    ImageRegression: typeof import('./src/components/fl-image-processor/ImageRegression.vue')['default']
    MatchAndCrop: typeof import('./src/components/fl-image-processor/MatchAndCrop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpcFileConverter: typeof import('./src/components/SpcFileConverter.vue')['default']
    ToolDocDrawer: typeof import('./src/components/ToolDocDrawer.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSlider: typeof import('@varlet/ui')['_SliderComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarStep: typeof import('@varlet/ui')['_StepComponent']
    VarSteps: typeof import('@varlet/ui')['_StepsComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
}
